### ISSUE TITLE
Does not work in Windows 7

### ISSUE THREAD

**Issue by joriguzman** [wmira/react-playground-vscode#4]
Throwing error:

extensionHost.ts:282[Extension Host] WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.context: The provided value "C:/Users/.../.vscode/extensions/wmira.react-playground-vscode-0.0.6" is not an absolute path!

**Comment by wmira** [comment]
@joriguzman thanks for the bug report. This has been fixed on 0.0.7
