### ISSUE TITLE
"You may need an appropriate loader to handle this file type." for JSX code

### ISSUE THREAD

**Issue by danielfranca** [wmira/react-playground-vscode#7]
Hey, 
I started using your extension for VS-Code, which looks pretty cool.
Unfortunately, I'm not being able to make it work in my project.

I keep receiving the message: You may need an appropriate loader to handle this file type.
Even having es2015, react and stage2 in babel-loader.

The full message for one of the files: https://pastebin.com/06VTuTvW

I, also, couldn't find how to reload after an error, even closing and re-opening the extension for different files doesn't work... it's always showing the first error.
The only way I found was disabling and re-enabling the extension, which can be annoying.

Am I missing something? Do I need to set the loader somewhere else so the extension understands it?

Specifications:
Mac OS X 10.12.4
VS Code: 1.12.1
React Playground: 0.0.10

Let me know.
Looking forward to use your extension.

**Comment by wmira** [comment]
Hi Daniel,

What loaders do you currently have on your project? I'm trying to make the loaders configurable or automatic.

Which version are you currently using? There was initial lifecycle issue which was closed I was wondering if that was your case.

Also which OS are you currently in?

Thanks.

**Comment by danielfranca** [comment]
Hi wmira, all this information is at the bottom of my post :)
My loaders are: es2015, react and stage2 in babel-loader.

Another thing worth to mention is I'm writing a Chrome Extension, so the setup is a bit different than usual.

**Comment by wmira** [comment]
@danielfranca they are babel presets and not loaders. Loaders are used by webpack. are you importing a different file other than js? a json perhaps?

**Comment by danielfranca** [comment]
@wmira The component I'm trying to render you mean? It's a jsx file.

To put in context, as a Chrome Extension it has 3 different "environments": content, background and popup. Each one has its own webpack config file, that's called by gulp to build the final extension.

As it's not located in a "default" location it might be the issue that the extension is not being able to find the webpack files?

The loader as I said is 'babel-loader' and I've presets for es2015, react and stage2.

btw I'm using webpack1

**Comment by wmira** [comment]
I see its a jsx file. I usually just load the jsx. Let me push a build to also include .jsx extension

**Comment by danielfranca** [comment]
Oh, I see it works for js files :) I changed some of my files to .js to test, and it worked except it can't find some of my directories.
Besides that there's any other way to reload the component without having to disable/enable the extension? Because after having one error I'm not being able to render anything else, tried to close/re-open the React Playground, I'd even tried to delete the .react-playground dir, but the render screen never updates.

**Comment by wmira** [comment]
It should auto reload  if you save again the file again. Let me try and recreate your issue. I think it has something to do when saving the dependency. Normally it should reload when you modify and save the main file.. 
I have push #9 for the jsx

**Comment by wmira** [comment]
@danielfranca  what kind of error did you get ( you saw the black page ? ) then fixing the error did not reload the view? I tried not closing the jsx, plugin throws error, then I fix error and save and the plugin reloaded the view.

Can you give me an exact steps you are experiencing so I can try to recreate?

**Comment by dcfranca** [comment]
@wmira Yes, I see the black page with "Failed to compile" message.
I tried saving the file, going to another component, saving the other component. Neither did work.

I'll update the plugin, thanks :)

**Comment by dcfranca** [comment]
Hey, after update all the files are working :) \o/ Thanks

The only issue now is that it's still not reloading, I mean, it reloads the same file if I save it, but if I go to a different file it doesn't update. Any idea why?

Silly question: There's a way to make it recognize my css I'm loading from a cdn? I've added the link to it into .react-playground/index.html and it works, but I'm afraid this is not the right thing to do as it might be overwritten.

**Comment by wmira** [comment]
import a css file e.g. App.css

import './App.css'

Then inside App.css

@import url('http.....')

**Comment by wmira** [comment]
@danielfranca make sure there is import React from 'react'; on the dependency files. At the moment it is not able to show that error ( I will see a way to pipe this out). Other than that the child dependency compilation/saving works for me and it reloads the main view.

Also if it happens that its not seem to reload try opening the developer tools.. Help - toggle developer tools and check if there is a message for the error.

**Comment by wmira** [comment]
@danielfranca which OS are you in?

**Comment by dcfranca** [comment]
Thanks, I'll try that. The css now is working fine :D

My OS is Mac OS X, it's at the bottom of my first post :)

**Comment by wmira** [comment]
oh bummer I don't have access to a Mac. See if the child dep is still an issue and paste here the dev tools error if there is.

**Comment by dcfranca** [comment]
Not sure if it's related to the child deps.
Maybe we're talking about different things

I'm trying to render each individual component separated.
I open a component and then I call the React-Playground... it works fine now.
Then I open another file, and I want to render this one now, but it doesn't update the view, I tried changing the file, saving, the dev tools don't show any error or similar.
Then I go back to the first file and it's working again, reloading every time I save.

To make it work with the second file I'd to disable/enable the extension, then open the second file first.

**Comment by dcfranca** [comment]
Another question, I see in the README that it's possible to set the properties, but I couldn't file where I can do that.

**Comment by wmira** [comment]
@danielfranca there is not an interactive way yet to pass in props -- will be on next major release im working at.. you can do this at the moment, Create a test bed file e.g. MyComponent.playground.js
and open launch playground on this file. This should also workaround the second window issue that you have. 
```javascript
// file MyComponent.playground.js

import React from 'react';
import { ComponentToTest } from './ComponentToTest';
import { AnotherToTest } from './AnotherToTest';

export const __PlaygroundTestComponent = () => {
    return (
        <ComponentToTest attribute='someattr'/>       
    );

}

export const __AnotherToTestComponent = () => {
    return (
        <AnotherToTest attribute='someattr'/>       
    );

}

```

**Comment by wmira** [comment]
#10 issue to allow multiple windows

**Comment by dcfranca** [comment]
Creating the file as you told works fine :) Thank you very much!

**Comment by wmira** [comment]
Thanks for the report  #10  and #11 should solve the other issues
